### PR TITLE
Reader implement io.Closer

### PR DESCRIPTION
**Pull request by reddingit**
So keep consistent use experience with gzip.Reader

### CODE REVIEW

**Comment by andybalholm** [comment]
Why not just use `io.NopCloser`?

**Comment by reddingit** [comment]
It can be done by `io.NopCloser`, but that smells not good.

**Comment by andybalholm** [comment]
I don't want to add a useless `Close` method that people will think they need to use.

**Comment by reddingit** [comment]
Ok, that's your rights.

**Pull request closed without merging**
